#pragma once

#define TDS_GAME_MSG_KILL_MELEE 256
#define TDS_GAME_MSG_CAMERA_TRACK 257
#define TDS_GAME_MSG_CAMERA_SHAKE 258
#define TDS_GAME_MSG_CAMERA_SIZE 259
#define TDS_GAME_MSG_PLAYER_HIT 260
#define TDS_GAME_MSG_PLAYER_ACTION 261
#define TDS_GAME_MSG_SAVESTATION_START 262
#define TDS_GAME_MSG_SAVESTATION_END 263
#define TDS_GAME_MSG_SAVESTATION_QUERY 264
#define TDS_GAME_MSG_WORLD_READY 265
